output   = "db/models"
wipe     = true
no-tests = true
add-global-variants = true
no-context = true
[psql]
  dbname = "confighub"
  host   = "localhost"
  port   = 5432
  user   = "root"
  pass   = ""
  schema = "public"
  sslmode = "disable"
  blacklist = ["goose_db_version"]
