apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "config-db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "config-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.extra.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "config-db.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.extra.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Chart.Name }}-sa
      {{- with .Values.extra.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.extra.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /app/config-db
          args:
            - serve
            - -vvv
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-connection-string
                  key: connection-string
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.extra.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.extra.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.extra.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
